name: login
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  flutter_staggered_grid_view: "^0.2.5"
  uuid: ^2.0.2
  get_version: ^0.1.0
  flutter_whatsnew: ^1.0.0
  native_widgets: ^1.0.1
  shared_preferences: ^0.5.3+4
  local_auth: ^0.6.0+1
  persist_theme: ^0.0.3+6
  scoped_model: ^1.0.1
  http: ^0.12.0+2
  json_annotation: ^3.0.0
  dio: 2.0.22


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.1
  json_serializable: ^3.2.2


flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
